### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by hatjs880328s** [zkrige/iOS-pkcs7-decrypt#1]
privateKey is pfx file path? 
cer is cer file path ? \

like this? 
let path = Bundle.main.path(forResource: "hello2", ofType: "txt")

        let plainTxt = try! String(contentsOfFile: path!)

        let privateKeyPath = "file:///var/mobile/Containers/Data/Application/EBC61F8F-CDA8-41BE-86ED-0DD51589D620/Documents/CloudDiskFile_257140_10000/shanwzh.pfx"

        let cerPath = "file:///var/mobile/Containers/Data/Application/EBC61F8F-CDA8-41BE-86ED-0DD51589D620/Documents/CloudDiskFile_257140_10000/hello.cer"

        let decrypted = PKCS7Decrypt.decrypt(plainTxt, privateKey: privateKeyPath, certificate: cerPath)

        return decrypted!

is plainTxt is base64 char?

**Comment by zkrige** [comment]
I posted an example in #2 

please let me know if that works for you
